author:
  name: Alex Sandri
  email: "me@alexsandri.com"

minima:
  skin: auto
  header_pages:
  social_links:
    - { platform: github,  user_url: "https://github.com/alex-sandri/prova-orale-allievi-marescialli-gdf-2023" }

remote_theme: jekyll/minima
